### ISSUE TITLE
Data Sharing and Privacy 

### ISSUE THREAD

**Issue by roychowd** [COVID-19-electronic-health-system/Corona-tracker#136] opened 2020-03-22 18:41 UTC
## Summary
@friedger made an excellent argument regarding Issue #113: We should consider restructuring the backend model to figure out how data will be shared so that it does not interfere with privacy laws. 

Example:
Sharing private data such as location should be done in accordance with privacy laws.

## Motivation
We need to be aware of the important legal and regulatory requirements of healthcare clients so we can avoid being liable in the future. Some standards to consider are HIPAA (US/CAN), GDPR (EU), etc..

## Describe alternatives you've considered
For anonymity, we could follow some de-identification steps found [here] (https://www.hhs.gov/hipaa/for-professionals/privacy/special-topics/de-identification/index.html#standard).

**Comment by ngiangre** [comment] 2020-03-22 19:45
I agree. Here's some points I made with @SomeMoosery:

1) Ownership: We can have permissions for everything (every data field essentially). At first, all input will be on the client side. After a set daily time, all data with the granted permissions e.g. an indicator function will be allowed to transfer when pulled from the client to our backend. This way the user owns the data they want to share.

2) Privacy: We are not a hipaa compliant entity: "HIPAA applies to healthcare providers, health plans, and healthcare clearinghouses if those organizations transmit health data electronically in connection with transactions for which the Department of Health and Human Services has adopted standards." source: https://www.hipaajournal.com/who-does-hipaa-apply-to/. If we work with an entity that is a hupaa compliant entity, then we have to be careful. Howeever, we're not financially liable: "Since the Enforcement Final Rule of 2006, OCR has had the power to issue financial penalties (and/or corrective action plans) to covered entities that fail to comply with HIPAA Rules." source: https://www.hipaajournal.com/what-are-the-penalties-for-hipaa-violations-7096/.

For v1: we can have anything we want set in the code because no one is using this yet. 

Prior to release, we can always take things out. As well as if we partner with a hipaa compliant entity we can not share some data with them based on field names. We can also add an attribute in the data model e.g. child to flag potential hipaa conflicting information.

I'm happy to hear GDPR regulations.

**Comment by suhacker1** [comment] 2020-03-23 00:42
Different privacy laws have different stipulations. Software like the ones developed by OneTrust exist to assist with compliance. Also, there are many privacy regulations that are on the verge of being passed. However, in general, privacy compliance ensures that users know what data is being collected from them, how it is being used, and have assurances regarding the risk of data collection. My suggestions are: 

1. Have a clear privacy policy that outlines the major information and data flows
2. Prepare an open source and accessible privacy impact assessment (PIA) 
3. Follow the seven principles of privacy by design. Implement privacy-preserving techniques from the onset. Instead of relying on just anonymization, it is likely worth investing in differential privacy. If machine learning is implemented, consider federated learning and secure multi-party computation as well 
4. Always ask for permission as @ngiangre stated

**Comment by ngiangre** [comment] 2020-03-23 01:39
We are and will further consider all of these points!

**Comment by SomeMoosery** [comment] 2020-04-11 02:27
Closing this issue as we've taken note of these security measures and will look to implement them ASAP

**Closed by SomeMoosery** 2020-04-11 02:27 UTC
Labels: discussion, long-term change
