### ISSUE TITLE
Set up continuous deployment 

### ISSUE THREAD

**Issue by njordhov** [COVID-19-electronic-health-system/Corona-tracker#270] opened 2020-03-29 00:28 UTC
## Summary

Set up _continuous deployment_ of the front-end from the github repo, serving a live app automatically built from the latest master.

## Motivation

Anyone can check out the current status of the project without having to build it locally.

## Additional context

We can deploy the front-end on a static site host such as [Netlify](https://docs.netlify.com/configure-builds/get-started/) and serve the back-end database etc elsewhere.

Issue #44 discusses deployment strategy for the back-end.

**Comment by SomeMoosery** [comment] 2020-03-29 16:02
Could this be a duplicate of #128 or is this something different? 

Definitely something we need to consider

**Comment by njordhov** [comment] 2020-03-29 19:53
> Could this be a duplicate of #128

It's similar but deployed each time you change master.
Easy to set up for anyone having write access to the repo.

**Comment by njordhov** [comment] 2020-03-29 21:17
I set up a continuous deployment based on my own fork of the repo:

https://amazing-murdock-40487c.netlify.com/

Here is the configuration:

![image](https://user-images.githubusercontent.com/219448/77861065-aa6e3000-71c7-11ea-9fda-2fd1b06d82cc.png)

**Comment by kevin-Price** [comment] 2020-04-16 03:19
This is a great idea. From my experience, Terraform + some scripts accomplish this very well. What pipeline were you thinking of using? Jenkins? AWS code pipeline?

**Comment by SomeMoosery** [comment] 2020-04-21 03:18
I'll start this process. Going to look to set up a pipeline to deploy changes to `corona-tracker-client` bucket when a PR merges in. I may also look to switch from Travis to Circle CI, as I'm a big fan of Circle CI and think it is great for modern solutions, but am open to suggestions on this and if it becomes more of a burden than it's worth, I'll just stick with Travis

**Closed** 2020-05-05 02:56 UTC
Labels: architecture
