### ISSUE TITLE
Looping circle after blockstack login

### ISSUE THREAD

**Issue by BrianHHough** [COVID-19-electronic-health-system/Corona-tracker#254] opened 2020-03-27 23:08 UTC
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Looping login // doesn't work, but it will work if you refresh browser or open in new window. Link to video in discord: https://discordapp.com/channels/687791378075484161/689541363254951951/692857336683036813

### Steps to Reproduce

1. Login with blockstack
2. Proceed
3. Looping black circle with black dot — cycles at top and doesn't go away or proceed to next screen.

**Expected behavior:**

Expect to go to homepage after log in directly.

**Actual behavior:**

Loop...or you have to refresh screen to go to homepage.

**Reproduces how often:**

Every time we log into blockstack

### Additional Information

Other people have had this issue too.

**Comment by SomeMoosery** [comment] 2020-03-27 23:36
Are there any error messages when running chrome dev tools (`Cmd+Optinon+i` on OSX)? Could be duplicate of #180

**Comment by njordhov** [comment] 2020-03-28 00:14
The endless spinner may happen if a Radiks server is not available at the configured or default URL, at least until #218 eventually has been addressed.

**Comment by SomeMoosery** [comment] 2020-04-11 02:37
@BrianHHough do you know if this has been resolved on your end? I haven't been able to reproduce this but want to be sure before closing.

**Comment by pavel-ilin** [comment] 2020-04-13 19:33
I and 3 test users haven't experienced this bug in 100% cases.

**Comment by SomeMoosery** [comment] 2020-04-13 21:12
I'll close this then!

**Closed by SomeMoosery** 2020-04-13 21:12 UTC
Labels: bug
